services:
  # Backend API service
  - type: web
    name: thinkflow
    env: node
    buildCommand: cd server && npm install
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

databases:
  - name: thinkflow-db
    plan: free
    databaseName: thinkflow
    user: thinkflow_user 